package hennyb.cotra.csv;

public enum CoTCSVHeader {

	MarketAndExchangeNames("Market and Exchange Names"),
	AsOfDateInFormYYMMDD("As of Date in Form YYMMDD"),
	AsOfDateInFormYYYYMMDD("As of Date in Form YYYY-MM-DD"),
	CFTCContractMarketCode("CFTC Contract Market Code"),
	CFTCMarketCodeInInitials("CFTC Market Code in Initials"),
	CFTCRegionCode("CFTC Region Code"),
	CFTCCommodityCode("CFTC Commodity Code"),
	OpenInterestAll("Open Interest (All)"),
	NoncommercialPositionsLongAll("Noncommercial Positions-Long (All)"),
	NoncommercialPositionsShortAll("Noncommercial Positions-Short (All)"),
	NoncommercialPositionsSpreadingAll("Noncommercial Positions-Spreading (All)"),
	CommercialPositionsLongAll("Commercial Positions-Long (All)"),
	CommercialPositionsShortAll("Commercial Positions-Short (All)"),
	TotalReportablePositionsLongAll(" Total Reportable Positions-Long (All)"),
	TotalReportablePositionsShortAll("Total Reportable Positions-Short (All)"),
	NonreportablePositionsLongAll("Nonreportable Positions-Long (All)"),
	NonreportablePositionsShortAll("Nonreportable Positions-Short (All)"),
	OpenInterestOld("Open Interest (Old)"),
	NoncommercialPositionsLongOld("Noncommercial Positions-Long (Old)"),
	NoncommercialPositionsShortOld("Noncommercial Positions-Short (Old)"),
	NoncommercialPositionsSpreadingOld("Noncommercial Positions-Spreading (Old)"),
	CommercialPositionsLongOld("Commercial Positions-Long (Old)"),
	CommercialPositionsShortOld("Commercial Positions-Short (Old)"),
	TotalReportablePositionsLongOld("Total Reportable Positions-Long (Old)"),
	TotalReportablePositionsShortOld("Total Reportable Positions-Short (Old)"),
	NonreportablePositionsLongOld("Nonreportable Positions-Long (Old)"),
	NonreportablePositionsShortOld("Nonreportable Positions-Short (Old)"),
	OpenInterestOther("Open Interest (Other)"),
	NoncommercialPositionsLongOther("Noncommercial Positions-Long (Other)"),
	NoncommercialPositionsShortOther("Noncommercial Positions-Short (Other)"),
	NoncommercialPositionsSpreadingOther("Noncommercial Positions-Spreading (Other)"),
	CommercialPositionsLongOther("Commercial Positions-Long (Other)"),
	CommercialPositionsShortOther("Commercial Positions-Short (Other)"),
	TotalReportablePositionsLongOther("Total Reportable Positions-Long (Other)"),
	TotalReportablePositionsShortOther("Total Reportable Positions-Short (Other)"),
	NonreportablePositionsLongOther("Nonreportable Positions-Long (Other)"),
	NonreportablePositionsShortOther("Nonreportable Positions-Short (Other)"),
	ChangeInOpenInterestAll("Change in Open Interest (All)"),
	ChangeInNoncommercialLongAll("Change in Noncommercial-Long (All)"),
	ChangeInNoncommercialShortAll("Change in Noncommercial-Short (All)"),
	ChangeInNoncommercialSpreadingAll("Change in Noncommercial-Spreading (All)"),
	ChangeInCommercialLongAll("Change in Commercial-Long (All)"),
	ChangeInCommercialShortAll("Change in Commercial-Short (All)"),
	ChangeInTotalReportableLongAll("Change in Total Reportable-Long (All)"),
	ChangeInTotalReportableShortAll("Change in Total Reportable-Short (All)"),
	ChangeInNonreportableLongAll("Change in Nonreportable-Long (All)"),
	ChangeInNonreportableShortAll("Change in Nonreportable-Short (All)"),
	PercentageOfOpenInterestOIAll("% of Open Interest (OI) (All)"),
	PercentageOfOINoncommercialLongAll("% of OI-Noncommercial-Long (All)"),
	PercentageOfOINoncommercialShortAll("% of OI-Noncommercial-Short (All)"),
	PercentageOfOINoncommercialSpreadingAll("% of OI-Noncommercial-Spreading (All)"),
	PercentageOfOICommercialLongAll("% of OI-Commercial-Long (All)"),
	PercentageOfOICommercialShortAll("% of OI-Commercial-Short (All)"),
	PercentageOfOITotalReportableLongAll("% of OI-Total Reportable-Long (All)"),
	PercentageOfOITotalReportableShortAll("% of OI-Total Reportable-Short (All)"),
	PercentageOfOINonreportableLongAll("% of OI-Nonreportable-Long (All)"),
	PercentageOfOINonreportableShortAll("% of OI-Nonreportable-Short (All)"),
	PercentageOfOpenInterestOIOld("% of Open Interest (OI)(Old)"),
	PercentageOfOINoncommercialLongOld("% of OI-Noncommercial-Long (Old)"),
	PercentageOfOINoncommercialShortOld("% of OI-Noncommercial-Short (Old)"),
	PercentageOfOINoncommercialSpreadingOld("% of OI-Noncommercial-Spreading (Old)"),
	PercentageOfOICommercialLongOld("% of OI-Commercial-Long (Old)"),
	PercentageOfOICommercialShortOld("% of OI-Commercial-Short (Old)"),
	PercentageOfOITotalReportableLongOld("% of OI-Total Reportable-Long (Old)"),
	PercentageOfOITotalReportableShortOld("% of OI-Total Reportable-Short (Old)"),
	PercentageOfOINonreportableLongOld("% of OI-Nonreportable-Long (Old)"),
	PercentageOfOINonreportableShortOld("% of OI-Nonreportable-Short (Old)"),
	PercentageOfOpenInterestOIOther("% of Open Interest (OI) (Other)"),
	PercentageOfOINoncommercialLongOther("% of OI-Noncommercial-Long (Other)"),
	PercentageOfOINoncommercialShortOther("% of OI-Noncommercial-Short (Other)"),
	PercentageOfOINoncommercialSpreadingOther("% of OI-Noncommercial-Spreading (Other)"),
	PercentageOfOICommercialLongOther("% of OI-Commercial-Long (Other)"),
	PercentageOfOICommercialShortOther("% of OI-Commercial-Short (Other)"),
	PercentageOfOITotalReportableLongOther("% of OI-Total Reportable-Long (Other)"),
	PercentageOfOITotalReportableShortOther("% of OI-Total Reportable-Short (Other)"),
	PercentageOfOINonreportableLongOther("% of OI-Nonreportable-Long (Other)"),
	PercentageOfOINonreportableShortOther("% of OI-Nonreportable-Short (Other)"),
	TradersTotalAll("Traders-Total (All)"),
	TradersNoncommercialLongAll("Traders-Noncommercial-Long (All)"),
	TradersNoncommercialShortAll("Traders-Noncommercial-Short (All)"),
	TradersNoncommercialSpreadingAll("Traders-Noncommercial-Spreading (All)"),
	TradersCommercialLongAll("Traders-Commercial-Long (All)"),
	TradersCommercialShortAll("Traders-Commercial-Short (All)"),
	TradersTotalReportableLongAll("Traders-Total Reportable-Long (All)"),
	TradersTotalReportableShortAll("Traders-Total Reportable-Short (All)"),
	TradersTotalOld("Traders-Total (Old)"),
	TradersNoncommercialLongOld("Traders-Noncommercial-Long (Old)"),
	TradersNoncommercialShortOld("Traders-Noncommercial-Short (Old)"),
	TradersNoncommercialSpreadingOld("Traders-Noncommercial-Spreading (Old)"),
	TradersCommercialLongOld("Traders-Commercial-Long (Old)"),
	TradersCommercialShortOld("Traders-Commercial-Short (Old)"),
	TradersTotalReportableLongOld("Traders-Total Reportable-Long (Old)"),
	TradersTotalReportableShortOld("Traders-Total Reportable-Short (Old)"),
	TradersTotalOther("Traders-Total (Other)"),
	TradersNoncommercialLongOther("Traders-Noncommercial-Long (Other)"),
	TradersNoncommercialShortOther("Traders-Noncommercial-Short (Other)"),
	TradersNoncommercialSpreadingOther("Traders-Noncommercial-Spreading (Other)"),
	TradersCommercialLongOther("Traders-Commercial-Long (Other)"),
	TradersCommercialShortOther("Traders-Commercial-Short (Other)"),
	TradersTotalReportableLongOther("Traders-Total Reportable-Long (Other)"),
	TradersTotalReportableShortOther("Traders-Total Reportable-Short (Other)"),
	ConcentrationGrossLT4TDRLongAll("Concentration-Gross LT = 4 TDR-Long (All)"),
	ConcentrationGrossLT4TDRShortAll("Concentration-Gross LT =4 TDR-Short (All)"),
	ConcentrationGrossLT8TDRLongAll("Concentration-Gross LT =8 TDR-Long (All)"),
	ConcentrationGrossLT8TDRShortAll("Concentration-Gross LT =8 TDR-Short (All)"),
	ConcentrationNetLT4TDRLongAll("Concentration-Net LT =4 TDR-Long (All)"),
	ConcentrationNetLT4TDRShortAll("Concentration-Net LT =4 TDR-Short (All)"),
	ConcentrationNetLT8TDRLongAll("Concentration-Net LT =8 TDR-Long (All)"),
	ConcentrationNetLT8TDRShortAll("Concentration-Net LT =8 TDR-Short (All)"),
	ConcentrationGrossLT4TDRLongOld("Concentration-Gross LT =4 TDR-Long (Old)"),
	ConcentrationGrossLT4TDRShortOld("Concentration-Gross LT =4 TDR-Short (Old)"),
	ConcentrationGrossLT8TDRLongOld("Concentration-Gross LT =8 TDR-Long (Old)"),
	ConcentrationGrossLT8TDRShortOld("Concentration-Gross LT =8 TDR-Short (Old)"),
	ConcentrationNetLT4TDRLongOld("Concentration-Net LT =4 TDR-Long (Old)"),
	ConcentrationNetLT4TDRShortOld("Concentration-Net LT =4 TDR-Short (Old)"),
	ConcentrationNetLT8TDRLongOld("Concentration-Net LT =8 TDR-Long (Old)"),
	ConcentrationNetLT8TDRShortOld("Concentration-Net LT =8 TDR-Short (Old)"),
	ConcentrationGrossLT4TDRLongOther("Concentration-Gross LT =4 TDR-Long (Other)"),
	ConcentrationGrossLT4TDRShortOther("Concentration-Gross LT =4 TDR-Short(Other)"),
	ConcentrationGrossLT8TDRLongOther("Concentration-Gross LT =8 TDR-Long (Other)"),
	ConcentrationGrossLT8TDRShortOther("Concentration-Gross LT =8 TDR-Short(Other)"),
	ConcentrationNetLT4TDRLongOther("Concentration-Net LT =4 TDR-Long (Other)"),
	ConcentrationNetLT4TDRShortOther("Concentration-Net LT =4 TDR-Short (Other)"),
	ConcentrationNetLT8TDRLongOther("Concentration-Net LT =8 TDR-Long (Other)"),
	ConcentrationNetLT8TDRShortOther("Concentration-Net LT =8 TDR-Short (Other)"),
	ContractUnits("Contract Units"),
	CFTCContractMarketCodeQuotes("CFTC Contract Market Code (Quotes)"),
	CFTCMarketCodeInInitialsQuotes("CFTC Market Code in Initials (Quotes)"),
	CFTCCommodityCodeQuotes("CFTC Commodity Code (Quotes)");


	private String header;
	
	CoTCSVHeader(String header) {
		
		this.header = header;
		
	}
	
	public String toString () {
		
		return this.header;
		
	}
	
}
